---
# develop with docker
driver:
  name: docker
  use_sudo: false
  provision_command: 
    - mkdir -p /run/sshd

provisioner:
  name: chef_zero
  root_path: /tmp/kitchen
  always_update_cookbooks: true
  retry_on_exit_code:
    - 35 # exit code signaling that the node is rebooting
  client_rb:
    client_fork: false # forked instances don't return the real exit code

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
  - name: ubuntu-18.04

suites:
  - name: default
    run_list:
      - recipe[docker_compose::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
