name 'docker_compose'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'All Rights Reserved'
description 'Installs/Configures docker_compose'
long_description 'Installs/Configures docker_compose'
version '0.1.0'
chef_version '>= 13.0'
gem 'octokit'
# issues_url 'https://github.com/<insert_org_here>/docker_compose/issues'
# source_url 'https://github.com/<insert_org_here>/docker_compose'
# depends 'github'

