name 'docker_compose'
maintainer 'The Authors'
maintainer_email 'rob@ferney.org'
license 'All Rights Reserved'
description 'Installs/Configures docker_compose'
long_description 'Installs/Configures docker_compose'
version '0.1.0'
chef_version '>= 13.0'
issues_url 'https://github.com/coquus-liber/docker_compose/issues'
source_url 'https://github.com/coquus-liber/docker_compose'
